name: 'javascript action example'
author: 'Takahiro Tominaga'
description: 'Custom github-action with TypeScript'

inputs:
  name:
    description: 'Name to greet'
    required: false
    default: 'John Doe'
  token:
    description: 'Github access token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
