name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action:
    name: Action-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check my action
        uses: kokoichi206/github-action-js-example@main

  action-without-install-node:
    name: Action-check-without-node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check my action
        uses: kokoichi206/github-action-js-example@main
